using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace SwitchBotMqttApp.Models.Enums;

[JsonConverter(typeof(JsonStringEnumMemberConverter))]
public enum DeviceType
{
    //PhysicalDevice
    Bot,
    Curtain,
    Curtain3,
    Hub,
    HubPlus,
    HubMini,
    Hub2,
    Meter,
    MeterPlus,
    OutdoorMeter,
    MeterPro,
    MeterProCO2,
    Lock,
    LockPro,
    Keypad,
    KeypadTouch,
    Remote,
    MotionSensor,
    ContactSensor,
    WaterDetector,
    CeilingLight,
    CeilingLightPro,
    PlugMiniUs,
    PlugMiniJp,
    Plug,
    StripLight,
    ColorBulb,
    RobotVacuumCleanerS1,
    RobotVacuumCleanerS1Plus,
    MiniRobotVacuumK10Plus,
    MiniRobotVacuumK10PlusPro,
    RobotVacuumCleanerS10,
    Humidifier,
    IndoorCam,
    PanTiltCam,
    BlindTilt,
    BatteryCirculatorFan,
    CirculatorFan,
    UniversalRemote,
    PanTiltCamPlus5mp,
    OutdoorSpotlightCam2K,
    WalletFinderCard,

    //VirtualInfraredRemoteDevice
    AirConditioner,
    TV,
    IPTV,
    SetTopBox,
    DVD,
    Fan,
    Projector,
    Camera,
    Others,
    AirPurifier,
    Speaker,
    WaterHeater,
    VacuumCleaner,
    Light,
}