version: '3.8'

services:
  switchbot-mqtt:
    image: ghcr.io/hsakoh/switchbotmqtt-amd64:1.0.28
    container_name: switchbot-mqtt
    volumes:
      - ./:/data
    ports:
      - "8099:8099"
      - "8098:8098"