name: "SwitchBot-Mqtt"
description: "Integrate SwitchBot Devices into Home Assistant via MQTT"
version: "1.0.16"
slug: "switchbot_mqtt"
url: "https://github.com/hsakoh/switchbot-mqtt"
ports:
  8098/tcp: 8098
startup: application
boot: manual
init: false
arch:
  - aarch64
  - amd64
services:
  - 'mqtt:need'
ingress: true
options:
  Mqtt: 
    AutoConfig: true
    Host: ''
    Port: 1883
    Id: ''
    Pw: ''
    Tls: false
  SwitchBot: 
    ApiKey: ''
    ApiSecret: ''
  EnforceDeviceTypes:
    - DeviceId : 'E2F67E000000(Example)'
      DeviceType : 'Curtain'
  WebhookService: 
    UseWebhook: true
    UseNgrok: true
    NgrokAuthToken: '<Configuration required only when using Webhook with ngrok>'
    HostUrl: '<Configuration required only when using Webhook without ngrok>'
  AutoStartServices: false
  LogLevel: 'Trace'
schema:
  Mqtt: 
    AutoConfig: bool
    Host: str?
    Port: "int(0,65535)?"
    Id: str?
    Pw: password?
    Tls: bool?
  SwitchBot: 
    ApiKey: str
    ApiSecret: password
  EnforceDeviceTypes:
    - DeviceId : str
      DeviceType : str
  WebhookService: 
    UseWebhook: bool
    UseNgrok: bool
    NgrokAuthToken: str?
    HostUrl: str?
  AutoStartServices: bool
  LogLevel: list(Trace|Debug|Information|Warning|Error|Critical|None)